# Generated by Django 5.0.6 on 2024-06-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.URLField()),
                ('redirect', models.URLField(blank=True, null=True)),
                ('words', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
