# Generated by Django 5.0.6 on 2024-06-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcount',
            name='classification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
