# Generated by Django 5.0.6 on 2024-06-14 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0002_wordcount_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.URLField(unique=True)),
                ('classification', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='wordcount',
            name='classification',
        ),
        migrations.AlterField(
            model_name='wordcount',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.host'),
        ),
    ]
