# Generated by Django 5.0.6 on 2024-06-21 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0004_host_create_time_host_last_check_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect', models.CharField(blank=True, max_length=200, null=True)),
                ('full_sentence', models.TextField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_sentences', to='classify.host')),
            ],
        ),
    ]
