# Generated by Django 5.0.6 on 2024-07-02 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0008_final_reporturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporturl',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.hosts'),
        ),
        migrations.AddField(
            model_name='hosts',
            name='final',
            field=models.CharField(default='정상', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Final',
        ),
    ]
